1. 2 ripe avacados
2. 1/4 teaspoon salt, or to taste
3. 1 tablespoon fresh lime juice or lemon juice
4. 2 tablespoons to 1/4 cup of minced red onion or thinly sliced green onion
5. 1-2 chiles, stems and seeds removed, finely chopped, add more to taste
6. 2 tablespoons cilantro (leaves and tender stems), finely chopped
7. A dash of freshly grated black pepper
8. 1/2 ripe tomato, seeds and pulp removed, chopped